from __future__ import annotations

BFS_SEARCH_S = 600.0
TOOL_CAP_S = 660.0
STEP_CHECK_S = 60.0
JAIL_EXTRA_S = 60.0

JAIL_BFS_SEARCH_S = BFS_SEARCH_S + JAIL_EXTRA_S
JAIL_TOOL_CAP_S = TOOL_CAP_S + JAIL_EXTRA_S
JAIL_STEP_CHECK_S = STEP_CHECK_S + JAIL_EXTRA_S
